version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data-volume:/var/lib/keycloak/data

volumes:
  keycloak-data-volume: