version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.1.1
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data-volume:/var/lib/keycloak/data

volumes:
  keycloak-data-volume: